@url = http://127.0.0.1:8000/

###
GET  {{url}}

###
POST {{url}}api/token/
Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}


###
POST {{url}}api/edit-post/
Content-Type: application/json

{
    "user_id": 3,
    "post_id": 1
}

###
POST {{url}}api/rate-post/
Content-Type: application/json

{
    "user_id": 3,
    "post_id": 1
}

###
POST {{url}}api/create-comment/
Content-Type: application/json

{
    "user_id": 1,
    "post_id": 1,
    "comment": "This is a comment2"
}

###
POST {{url}}api/friend-request/
Content-Type: application/json

{
  "username_id": 1,
  "friend_id": 2
}



###
