# Generated by Django 4.1.7 on 2023-04-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=9999, null=True, upload_to='profile_pictures/'),
        ),
    ]
