# Generated by Django 4.1.7 on 2023-04-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
