# Generated by Django 4.1.7 on 2023-04-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_post_liked_by_remove_user_likes_post_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='users/<django.db.models.fields.related.ForeignKey>/posts/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=9999, null=True, upload_to='users/<django.db.models.fields.CharField>/avatar/'),
        ),
    ]
