# Generated by Django 4.1.7 on 2023-04-03 14:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_profiledata_alter_comment_user_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileData',
            new_name='Profile',
        ),
    ]
