# Generated by Django 4.2 on 2023-04-06 19:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_post_friend_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='friend_request',
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_request',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
