# Generated by Django 4.2 on 2023-04-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_post_friend_request_profile_friend_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend_request',
        ),
    ]
